name: Run Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose the environment"
        required: true
        default: "stage"
        type: environment

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Create .env file
        run: |
          echo "HEADLESS=${{ env.HEADLESS }}" >> .env

      - name: Install Dependencies
        run: npm install
        
      - name: Install Chromium Driver
        run: npx playwright install chromium

      - name: Run Tests
        env:
          SELECTED_ENV: ${{ github.event.inputs.environment }}
        run: |
          echo "Running tests for $SELECTED_ENV environment"
          if [ "$SELECTED_ENV" = "stage" ]; then
            echo "Using stage environment"
            npm test
          elif [ "$SELECTED_ENV" = "service-stacks" ]; then
            echo "Using service-stacks environment"
            npm test
          else
            echo "Invalid environment selected"
            exit 1
          fi
